### ISSUE TITLE
I keep getting a node modules Error when i load it from "import RichTextEditor from 'react-rte/lib/RichTextEditor';"

### ISSUE THREAD

**Issue by BbosaH** [sstur/react-rte#240]
I am using this editor and i think its good. I am using Webpack. I keep getting this Error. . 

`
ERROR in ./node_modules/css-loader!./node_modules/react-rte/lib/ui/IconButton.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".icon-undo", ".icon-undo" is weird
    at C:\projects\aurity\reactweb\node_modules\postcss-modules-scope\lib\index.js:26:13
    at Array.map (native)
    at getSingleLocalNamesForComposes (C:\projects\aurity\reactweb\node_modules\postcss-modules-scope\lib\index.js:20:26)
    at C:\projects\aurity\reactweb\node_modules\postcss-modules-scope\lib\index.js:106:26
    at C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:198:28
    at C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:148:26
    at Rule.each (C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:114:22)
    at Rule.walk (C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:147:21)
    at Rule.walkDecls (C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:196:25)
    at C:\projects\aurity\reactweb\node_modules\postcss-modules-scope\lib\index.js:105:12
    at C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:241:28
    at C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:148:26
    at Root.each (C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:114:22)
    at Root.walk (C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:147:21)
    at Root.walkRules (C:\projects\aurity\reactweb\node_modules\postcss\lib\container.js:239:25)
    at C:\projects\aurity\reactweb\node_modules\postcss-modules-scope\lib\index.js:101:9
    at LazyResult.run (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:274:20)
    at LazyResult.asyncTick (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:189:32)
    at LazyResult.asyncTick (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:228:20)
    at LazyResult.async (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:225:27)
    at LazyResult.then (C:\projects\aurity\reactweb\node_modules\postcss\lib\lazy-result.js:131:21)
    at processCss (C:\projects\aurity\reactweb\node_modules\css-loader\lib\processCss.js:212:5)
    at Object.module.exports (C:\projects\aurity\reactweb\node_modules\css-loader\lib\loader.js:40:2)
 @ ./node_modules/react-rte/lib/ui/IconButton.css 4:14-72
 @ ./node_modules/react-rte/lib/ui/IconButton.js
 @ ./node_modules/react-rte/lib/lib/EditorToolbar.js
 @ ./node_modules/react-rte/lib/RichTextEditor.js
 @ ./app/containers/container-create-article.container.jsx
 @ ./app/containers/container-share-knowledge-options.container.jsx`

**Comment by HenokT** [comment]
Make sure the CSS Modules spec is enabled by passing the "modules" query parameter to your css-loader:
``` 
 {
    test: /\.css$/,
    loaders: [
      'style-loader',
      'css-loader?modules'
    ]
  }
```

**Comment by DougWoodCDS** [comment]
for those with latest version of webpack 

```
  {
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  modules: true,
                  importLoaders: 1,
                },
              },
```

**Comment by w-** [comment]
@DougWoodCDS  Thank you

**Comment by geebengs** [comment]
Please, how can I use this editor with create-react-app? As I can't edit webpack config in create-react-app without first ejecting it

**Comment by HenokT** [comment]
> Please, how can I use this editor with create-react-app? As I can't edit webpack config in create-react-app without first ejecting it

In create-react-app, CSS Modules are turned on for files ending with the .module.css extension. 

https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet

**Comment by matiastucci** [comment]
I'm getting the same error but I'm using next.js and my next.config.js looks like this:

```js

const withCSS = require('@zeit/next-css')
const withLess = require('@zeit/next-less')
const withSass = require('@zeit/next-sass')

if (typeof require !== 'undefined') {
  require.extensions['.less'] = () => {}
}

module.exports = withCSS(
  withLess(
    withSass({
      lessLoaderOptions: {
        javascriptEnabled: true,
      },
    })
  )
)

```

any ideas?

**Comment by nehahirve** [comment]
Hey! I used this module in gatsby and got the same errors on build. When I added the css loader to the webpack config it 

What fixed it for me is changing the iconButton.css to an iconButton.module.css, which gatsby recognised, but then my styling disappeared. turned out the icon-bold etc classes weren't working due to the hyphen, so i changed the classnames and it worked fine. 

Is this something I should make a PR for? It would be my first, i'm a newbie and not sure if this is something that should be fixed.
