### ISSUE TITLE
Server Side Rendering Problem

### ISSUE THREAD

**Issue by ZeroCho** [sstur/react-rte#37]
I use server-side-rendering with react and webpack based on react-webpack-node.
Does react-rte use jquery? Or, is it draft-js that use jquery?
I don't use jquery in my project but after I installed react-rte,
console shows me an error message that
```
var $ = window.jQuery || window.Zepto;
              ^
TypeError: cannot find property 'jQuery' of undefined
```
So, I think this is because nodejs server doesn't know window object...
Is there possible solution for this??

**Comment by sstur** [comment]
That's so weird. Nothing in react-rte or draft-js uses jQuery. Do you have a stack trace to go with that error?

Weirdly still, the TypeError says cannot find property 'jquery' yet the line is asking for jQuery (case difference).

I wonder if this could be related to jsdom which I'm using in my tests. You could try setting `global.window = global` and see if that makes the error disappear, since the actual error is not related to jQuery or Zepto but the fact that window is undefined.

**Comment by ZeroCho** [comment]
Oops. It was jQuery not jquery. I changed it.
I have a stack trace but it is useless because it shows the result after being webpacked.
like the following
```
TypeError: Cannot read property 'jQuery' of undefined
    at C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:38109:29
    at Object.<anonymous> (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:38124:5)
    at Object.module.exports.module.exports.module.deprecate (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:38125:32)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.module.exports._typeof (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:37368:18)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.<anonymous> (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:37115:23)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.<anonymous> (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:37015:19)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.module.exports._typeof (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:36804:29)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.module.exports._typeof (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:36564:25)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.module.exports._typeof (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:36281:26)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.module.exports.module.exports.BOLD.fontWeight (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:32672:29)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.<anonymous> (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:31322:21)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
    at Object.<anonymous> (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30974:18)
    at __webpack_require__ (C:\Users\ZeroCho\WebstormProjects\zerocho-home\public\server.js:30934:31)
```
but as I followed the stack trace, 

it shows DraftJS -> DraftEditor -> DraftEditorContents -> DraftEditorBlock -> DraftEditorLeaf -> DraftEditorTextNode -> UserAgent -> UserAgentData -> UAParser
then some codes like this
`(typeof window === 'undefined' ? 'undefined' : _typeof(window)) === 'object' ? window : undefined)`

yes, I don't think it's your react-rte problem...
By the way, where should I put `global.window = global`? In the server file?

**Comment by sstur** [comment]
I was thinking you could try putting `global.window = global;` somewhere early in your loading chain. Maybe in your main file before you call your first require/import. It's just a guess really, I have no idea if it will fix anything.

**Comment by ZeroCho** [comment]
Finally solved by not using react-rte on server-side-rendering
I just wrapped import codes with if (process.env.BROWSER) and render only if it is browser environment.
Still mysterious why this problem happens

**Comment by NotBrianZach** [comment]
I also had this problem in a project based on this repo: https://github.com/erikras/react-redux-universal-hot-example
