### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by abejfehr** [sstur/react-rte#81]
I was having the same issue as #55, but thankfully I found [this](https://www.npmjs.com/package/react-rte-browserify) package which solves the issue. 

_Now_, I'm unable to server-side render this because somewhere in this package, something is bound to the `window` object, which doesn't exist in the NodeJS server that's rendering the content. 

Is there any way to use this plugin without `window`?

**Comment by ZeroCho** [comment]
#37 #50 
this issue is related to draft-js as far as i know

**Comment by abejfehr** [comment]
I'm making my own editor now that uses DraftJS and so far I've been able to do server-side rendering just fine. I don't think DraftJS requires jQuery anywhere, at least [I can't find any evidence of it in their repo](https://github.com/facebook/draft-js/search?utf8=%E2%9C%93&q=jquery).

**Comment by ZeroCho** [comment]
@abejfehr draft-js uses us-parser-js and it requires jquery

**Comment by abejfehr** [comment]
I see, that's a complicated string of dependencies. Either way, I'm able to get draft-js alone working isomorphically, so it must be some specific action that's getting it to a point where `window` is required.

As I've already started using draft-js to make my own simple editor, I'm not very worried about tracking this exact bug down. You may close this issue if you wish

**Comment by ZeroCho** [comment]
I'm not the owner of this repo, and I really wanted to solve this problem too

**Comment by rkoberg** [comment]
Same here. Draft-JS runs fine isomorphically, but react-rte errors on the server side render causing the server to not return a page. In other words, it breaks so that nothing reaches the browser.

**Comment by rkoberg** [comment]
```
/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19795
			return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
			                           ^

ReferenceError: window is not defined
    at /Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19795:31
    at /Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19790:48
    at module.exports (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19812:69)
    at Object.<anonymous> (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19690:39)
    at __webpack_require__ (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:21:30)
    at Object.module.exports.exports.__esModule (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19555:16)
    at __webpack_require__ (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:21:30)
    at Object.module.exports.hasOwn (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19404:16)
    at __webpack_require__ (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:19321:20)
    at __webpack_require__ (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:18948:21)
    at __webpack_require__ (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:21:30)
    at Object.<anonymous> (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:89:23)
    at __webpack_require__ (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:21:30)
    at module.exports.Object.defineProperty.value (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:41:18)
    at Object.<anonymous> (/Users/rkoberg/Sites/fwi/node_modules/react-rte/dist/react-rte.js:44:10)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rkoberg/Sites/fwi/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by pnmsharma** [comment]
try this link:
https://github.com/webpack/style-loader/pull/115/files

**Comment by ZeroCho** [comment]
@pnmsharma Pull Request that you linked is closed. Sokra said to use css/locals instead.

**Comment by ZeroCho** [comment]
@abejfehr @rkoberg I think it's related with style-loader. This package uses style-loader to style, but style-loader can't be used in SSR

**Comment by sstur** [comment]
Yes, I think this is related to Webpack CSS Modules/Style Loader. I will close this in favor of tracking the issue in #77. Please follow that one for updates. I do have a plan that I think will fix it.

**Comment by dheerajmpai** [comment]
This has nothing to do with CSS modules. But it is closed in the name as so
